#!/usr/bin/sh
set -eu

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

cat > "$tmp" <<'EOF'
GTK_IM_MODULE=fcitx
QT_IM_MODULE=fcitx
QT_IM_MODULES="wayland;fcitx"
XMODIFIERS=@im=fcitx
SDL_IM_MODULE=fcitx
EOF

install -m 0644 "$tmp" /etc/environment
