#include "grubconfig.h"

#include <QDir>
#include <QFile>
#include <QFileInfo>
#include <QRegularExpression>
#include <QStringList>
#include <QTextStream>

#ifndef GRUB_DEFAULT_PATH
#define GRUB_DEFAULT_PATH "/etc/default/grub"
#endif

#ifndef BLS_ENTRIES_PATH
#define BLS_ENTRIES_PATH "/boot/loader/entries"
#endif

GrubConfig::GrubConfig(QObject *parent)
    : QObject(parent)
{
    parseCurrentCmdline();
}

bool GrubConfig::load()
{
    QFile file(QStringLiteral(GRUB_DEFAULT_PATH));
    if (!file.exists()) {
        // /etc/default/grub 不存在，从 BLS 条目回退读取
        loadFromBls();
        return true;
    }

    if (!file.open(QIODevice::ReadOnly | QIODevice::Text)) {
        return false;
    }

    QTextStream stream(&file);
    parseConfigContent(stream.readAll());
    return true;
}

QString GrubConfig::generateConfigContent() const
{
    QStringList lines;
    lines << QStringLiteral("# Generated by Miryu GRUB2 Boot Config");
    lines << QStringLiteral("# These settings are merged into /etc/default/grub by the helper.");
    lines << QString();
    lines << QStringLiteral("GRUB_TIMEOUT_STYLE=%1").arg(m_showMenu ? QStringLiteral("menu")
                                                                    : QStringLiteral("hidden"));
    lines << QStringLiteral("GRUB_TIMEOUT=%1").arg(m_timeout);

    if (m_rememberLast) {
        lines << QStringLiteral("GRUB_DEFAULT=saved");
        lines << QStringLiteral("GRUB_SAVEDEFAULT=true");
    } else {
        lines << QStringLiteral("GRUB_DEFAULT=0");
        lines << QStringLiteral("GRUB_SAVEDEFAULT=false");
    }

    const QString params = escapedBootParams();
    lines << QStringLiteral("GRUB_CMDLINE_LINUX=\"%1\"").arg(params);

    return lines.join(QLatin1Char('\n')) + QLatin1Char('\n');
}

void GrubConfig::parseConfigContent(const QString &content)
{
    const QRegularExpression styleRe(QStringLiteral(R"(^\s*GRUB_TIMEOUT_STYLE\s*=\s*(menu|hidden)\s*$)"),
                                     QRegularExpression::MultilineOption);
    auto match = styleRe.match(content);
    if (match.hasMatch()) {
        m_showMenu = match.captured(1) == QStringLiteral("menu");
    }

    const QRegularExpression timeoutRe(QStringLiteral(R"(^\s*GRUB_TIMEOUT\s*=\s*(-?\d+)\s*$)"),
                                       QRegularExpression::MultilineOption);
    match = timeoutRe.match(content);
    if (match.hasMatch()) {
        m_timeout = match.captured(1).toInt();
    }

    m_rememberLast = content.contains(QRegularExpression(QStringLiteral(R"(^\s*GRUB_DEFAULT\s*=\s*saved\s*$)"),
                                                         QRegularExpression::MultilineOption))
                     && content.contains(QRegularExpression(QStringLiteral(R"(^\s*GRUB_SAVEDEFAULT\s*=\s*true\s*$)"),
                                                            QRegularExpression::MultilineOption));

    const QRegularExpression cmdlineRe(QStringLiteral(R"REX(^\s*GRUB_CMDLINE_LINUX\s*=\s*"((?:\\.|[^"\\])*)"\s*$)REX"),
                                       QRegularExpression::MultilineOption);
    match = cmdlineRe.match(content);
    if (match.hasMatch()) {
        QString params = match.captured(1);
        params.replace(QStringLiteral("\\\""), QStringLiteral("\""));
        params.replace(QStringLiteral("\\\\"), QStringLiteral("\\"));
        m_bootParams = params.trimmed();
    }
}

void GrubConfig::parseCurrentCmdline()
{
    QFile file(QStringLiteral("/proc/cmdline"));
    if (!file.open(QIODevice::ReadOnly | QIODevice::Text)) {
        return;
    }

    QTextStream stream(&file);
    m_currentCmdline = stream.readAll().trimmed();
}

void GrubConfig::loadFromBls()
{
    const QDir blsDir(QStringLiteral(BLS_ENTRIES_PATH));
    if (!blsDir.exists()) {
        return;
    }

    // 获取当前运行的内核版本
    QString kernelVersion;
    QFile osrelease(QStringLiteral("/proc/sys/kernel/osrelease"));
    if (osrelease.open(QIODevice::ReadOnly | QIODevice::Text)) {
        kernelVersion = QString::fromUtf8(osrelease.readAll()).trimmed();
        osrelease.close();
    }

    if (kernelVersion.isEmpty()) {
        return;
    }

    // 遍历 BLS 条目，找到与当前内核匹配的条目
    const QStringList filters(QStringLiteral("*.conf"));
    const QFileInfoList entries = blsDir.entryInfoList(filters, QDir::Files, QDir::Name);

    for (const QFileInfo &entryInfo : entries) {
        QFile file(entryInfo.absoluteFilePath());
        if (!file.open(QIODevice::ReadOnly | QIODevice::Text)) {
            continue;
        }

        QTextStream stream(&file);
        const QString content = stream.readAll();
        file.close();

        QString versionLine;
        QString linuxLine;
        QString optionsLine;

        for (const QString &rawLine : content.split(QLatin1Char('\n'))) {
            const QString line = rawLine.trimmed();
            if (line.startsWith(QStringLiteral("version "))) {
                versionLine = line.mid(QStringLiteral("version ").length()).trimmed();
            } else if (line.startsWith(QStringLiteral("linux "))) {
                linuxLine = line.mid(QStringLiteral("linux ").length()).trimmed();
            } else if (line.startsWith(QStringLiteral("options "))) {
                optionsLine = line.mid(QStringLiteral("options ").length()).trimmed();
            }
        }

        // 匹配当前内核版本
        const bool versionMatch = !versionLine.isEmpty() && versionLine == kernelVersion;
        const bool linuxMatch = linuxLine.contains(kernelVersion);

        if (!versionMatch && !linuxMatch) {
            continue;
        }

        // 提取内核参数，过滤掉系统级参数（root= 和 ro）
        if (!optionsLine.isEmpty()) {
            QStringList filtered;
            for (const QString &param : optionsLine.split(QLatin1Char(' '), Qt::SkipEmptyParts)) {
                if (param.startsWith(QStringLiteral("root="))) {
                    continue;
                }
                if (param == QStringLiteral("ro")) {
                    continue;
                }
                filtered << param;
            }
            m_bootParams = filtered.join(QLatin1Char(' '));
        }
        break;
    }
}

QString GrubConfig::escapedBootParams() const
{
    QString params = m_bootParams.trimmed();
    params.replace(QLatin1Char('\\'), QStringLiteral("\\\\"));
    params.replace(QLatin1Char('"'), QStringLiteral("\\\""));
    return params;
}
